#!/usr/bin/env bash

BASEDIR="$PWD"

if ! [ -e "${BASEDIR}"/qmk_firmware/keyboards/planck/keymaps/pcheng ]; then
    echo "Creating symlink for qmk_firmware/keyboards/planck/keymaps/pcheng"
    ln -s "${BASEDIR}"/keyboards/planck/keymaps/pcheng "${BASEDIR}"/qmk_firmware/keyboards/planck/keymaps/pcheng
else
    echo "Symlink for qmk_firmware/keyboards/planck/keymaps/pcheng already exists"
fi

if ! [ -e "${BASEDIR}"/qmk_firmware/keyboards/keebio/levinson/keymaps/pcheng ]; then
    echo "Creating symlink for qmk_firmware/keyboards/keebio/levinson/keymaps/pcheng"
    ln -s "${BASEDIR}"/keyboards/keebio/levinson/keymaps/pcheng "${BASEDIR}"/qmk_firmware/keyboards/keebio/levinson/keymaps/pcheng
else
    echo "Symlink for qmk_firmware/keyboards/keebio/levinson/keymaps/pcheng already exists"
fi
