name: Build crkbd/rev1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Create symlinks
      run: python3 ./setup.py
    - name: Build firmware
      run: |
       make -C qmk_firmware crkbd:pcheng
       make -C qmk_firmware crkbd:pcheng_mac
    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: crkbd_rev1
        path: |
         ./qmk_firmware/crkbd_rev1_pcheng.hex
         ./qmk_firmware/crkbd_rev1_pcheng_mac.hex
