name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Create symlinks
      run: python ./setup.py
    - name: Build firmware
      run: make -C qmk_firmware keebio/levinson/rev3:pcheng
